### ISSUE TITLE
WASM compilation fails when combining let-bound handle with specific effect sequences

### ISSUE THREAD

**Issue by Kroisse** [Kroisse/tribute#190]
## Summary

WASM compilation fails with "wasm.if then region missing result value" when combining:
1. Let-bound handle expression (`let req = handle comp(); case req { ... }`)
2. Additional effect operations in the computation closure

Each change works independently, but combining them causes a compilation failure.

## Reproduction

**Working code (current `lang-examples/ability_core.trb`):**
```tribute
ability State(s) {
    fn get() -> s
    fn set(value: s) -> Nil
}

fn counter() ->{State(Int)} Int {
    let n = State::get()
    State::set(n + 1)
    n
}

fn run_state(comp: fn() ->{e, State(s)} a, init: s) ->{e} a {
    case handle comp() {
        { result } -> result
        { State::get() -> k } -> run_state(fn() { k(init) }, init)
        { State::set(v) -> k } -> run_state(fn() { k(Nil) }, v)
    }
}

fn main() -> Int {
    run_state(fn() {
        counter()
        counter()
        counter()
    }, 0)
}
```

**Change A (let-bound handle) - works alone:**
```diff
 fn run_state(comp: fn() ->{e, State(s)} a, init: s) ->{e} a {
-    case handle comp() {
+    let req = handle comp()
+    case req {
         { result } -> result
         { State::get() -> k } -> run_state(fn() { k(init) }, init)
         { State::set(v) -> k } -> run_state(fn() { k(Nil) }, v)
     }
 }
```

**Change B (State::set in main closure) - works alone:**
```diff
 fn main() -> Int {
     run_state(fn() {
         counter()
         counter()
         counter()
+        State::set(42)
     }, 0)
 }
```

**Change A + B combined - FAILS:**
```
Error: Compilation failed: invalid module: wasm.if then region missing result value
```

## Analysis

The issue appears to be in the WASM emit phase. When combining:
- Let-bound handle (separating `handle` from `case` creates intermediate binding)
- Additional effect operations in the computation closure

...the emit phase fails to properly handle the result value flow in the generated `wasm.if` then region.

Each change individually works, suggesting an interaction between:
1. How let-bound handle results are represented in IR
2. How yield bubbling interacts with the closure body

## Environment

- Target: WasmGC
- Affected pass: `emit.rs` (WASM emission)

## Related

- PR #191: YieldResult yield bubbling implementation
- Milestone: Ability System (Core) ✅

**Comment by Kroisse** [comment]
This issue is no longer valid. The request-as-value pattern (`let req = handle comp()`) was removed in the CPS/trampoline-based handler implementation. Handle expressions are now syntactically integrated with their case arms.
